TripodReporter.Web/Controllers/PoliciesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using TripodReporter.Domain.Contexts;
using TripodReporter.Domain.Entities;
using TripodReporter.Domain.Repositories;
using TripodReporter.Web.Infrastructure;


namespace TripodReporter.Web.Controllers
{
    public class PoliciesController : Controller
    {
        private IRepository<Policy> repo;
        private IRepository<Client> repo1;
        private IRepository<Insurer> repo2;

        public PoliciesController(IRepository<Policy> db, IRepository<Client> db1, IRepository<Insurer> db2)
        {
            repo = db;
            repo1 = db1;
            repo2 = db2;
        }

        // GET: Policies
        public ActionResult Index()
        {
            //This line is to include Client & Insurer Table data in Listing Policices
            //Think of including exception handling for odd errors
            var ToInclude = repo.GetAll().AsQueryable().Include(p => p.Client).Include(p => p.Insurer);
            //ToInclude.Where(x => x.PolicyDate.Year == 2014).ToList();
            return View(ToInclude.ToList());
            //return View(ToInclude.Where(x => x.PolicyDate.Year == 2014).ToList());
        }

        public void _ToExcel()
        {
            //You want to export to excel using this method
            System.Web.UI.WebControls.GridView gv = new System.Web.UI.WebControls.GridView();
            gv.DataSource = repo.GetAll().AsQueryable().Include(p => p.Client).Include(p => p.Insurer).ToList().Take(5);
            gv.DataBind();
            Response.ClearContent();
            Response.AddHeader("content-dispostion", "attachment;filename=report.xls");
            Response.ContentType = "application/ms-excel";
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            gv.RenderControl(htw);
            Response.Write(sw.ToString());
            //Response.WriteFile()
            Response.End();
            RedirectToAction("index");
        }

        [HttpPost]
        public ExcelResult ExportToExcel()
        {
            //created an excelresult type and make the table on screen an excel sheet.
            System.Web.UI.WebControls.GridView gv = new System.Web.UI.WebControls.GridView();
            gv.DataSource = repo.GetAll().AsQueryable().Include(p => p.Client).Include(p => p.Insurer).ToList().Take(5);
            gv.DataBind();
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            gv.RenderControl(htw);
            return new ExcelResult{
                stringwriter = sw.ToString()
            };
        }
        

        // GET: Policies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Policy policy = repo.Query(x => x.PolicyId == id).Single();
            if (policy == null)
            {
                return HttpNotFound();
            }
            return View(policy);
        }

        // GET: Policies/Create
        public ActionResult Create()
        {
            //ViewBag.ClientId = new SelectList(db.Clients, "ClientId", "ClientName");
            //ViewBag.InsurerId = new SelectList(db.Insurers, "InsurerId", "Name");

            
            ViewBag.ClientId = new SelectList(repo1.GetAll(), "ClientId", "ClientName");
            ViewBag.InsurerId = new SelectList(repo2.GetAll(), "InsurerId", "Name");
            return View();
        }

        // POST: Policies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PolicyId,ClientId,PolicyNumber,InsurerId,PolicyDetails,PolicyType,PolicyDate,PolicyValue,PremiumPaid,Comission")] Policy policy)
        {
            if (ModelState.IsValid)
            {
                repo.Add(policy);
                repo.Commit();
                return RedirectToAction("Index");
            }
            ViewBag.ClientId = new SelectList(repo1.GetAll(), "ClientId", "ClientName", policy.ClientId);
            ViewBag.InsurerId = new SelectList(repo2.GetAll(), "InsurerId", "Name", policy.InsurerId);
            
            return View(policy);
        }

        // GET: Policies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Policy policy = repo.Query(e => e.PolicyId == id).Single();
            if (policy == null)
            {
                return HttpNotFound();
            }

            ViewBag.ClientId = new SelectList(repo1.GetAll(), "ClientId", "ClientName", policy.ClientId);
            ViewBag.InsurerId = new SelectList(repo2.GetAll(), "InsurerId", "Name", policy.InsurerId);
            return View(policy);
        }

        // POST: Policies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PolicyId,ClientId,PolicyNumber,InsurerId,PolicyDetails,PolicyType,PolicyDate,PolicyValue,PremiumPaid,Comission")] Policy policy)
        {
            if (ModelState.IsValid)
            {
                repo.AddOrUpdate(policy);
                repo.Commit();
                return RedirectToAction("Index");
            }
           
            ViewBag.ClientId = new SelectList(repo1.GetAll(), "ClientId", "ClientName", policy.ClientId);
            ViewBag.InsurerId = new SelectList(repo2.GetAll(), "InsurerId", "Name", policy.InsurerId);
            return View(policy);
        }

        // GET: Policies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Policy policy = repo.Query(d => d.PolicyId == id).Single();
            if (policy == null)
            {
                return HttpNotFound();
            }
            return View(policy);
        }

        // POST: Policies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Policy policy = repo.Query(d => d.PolicyId == id).Single();
            repo.Delete(policy);
            repo.Commit();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repo.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TripodReporter.Web/Views/Policies/Create.cshtml
@model TripodReporter.Domain.Entities.Policy

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Policy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, "ClientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PolicyNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PolicyNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InsurerId, "InsurerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("InsurerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InsurerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.PolicyDetails, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PolicyDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.PolicyType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PolicyType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PolicyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PolicyDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PolicyValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PolicyValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PremiumPaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PremiumPaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PremiumPaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comission, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comission, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TripodReporter.Web/Views/Policies/Delete.cshtml
@model TripodReporter.Domain.Entities.Policy

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Policy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.ClientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.ClientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Insurer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Insurer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolicyNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolicyNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolicyDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolicyDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolicyType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolicyType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolicyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolicyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolicyValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolicyValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PremiumPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PremiumPaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comission)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TripodReporter.Web/Views/Policies/Details.cshtml
@model TripodReporter.Domain.Entities.Policy

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Policy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.ClientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.ClientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Insurer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Insurer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolicyNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolicyNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolicyDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolicyDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolicyType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolicyType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolicyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolicyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolicyValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolicyValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PremiumPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PremiumPaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comission)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comission)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PolicyId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TripodReporter.Web/Views/Policies/Edit.cshtml
@model TripodReporter.Domain.Entities.Policy

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Policy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PolicyId)

        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, "ClientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PolicyNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PolicyNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InsurerId, "InsurerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("InsurerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InsurerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.PolicyDetails, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PolicyDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.PolicyType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PolicyType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PolicyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PolicyDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PolicyValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PolicyValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PremiumPaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PremiumPaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PremiumPaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comission, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comission, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TripodReporter.Web/Views/Policies/Index.cshtml
@model IEnumerable<TripodReporter.Domain.Entities.Policy>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (@Html.BeginForm("ExportToExcel", "Policies")) { 
<p>
    <input type="submit" value="Export Data" class="btn btn-default" />
</p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Client.ClientName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Insurer.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PolicyNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PolicyDetails)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PolicyType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PolicyDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PolicyValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PremiumPaid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comission)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Client.ClientName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Insurer.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PolicyNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PolicyDetails)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PolicyType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PolicyDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PolicyValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PremiumPaid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comission)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PolicyId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PolicyId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PolicyId })
        </td>
    </tr>
}

</table>